<?php

return [
    'fields'=>
        [
            'seo_title',
            'seo_description',
            'seo_keywords'
        ],
    'owners'=>
        [
            'slider',
            'about',
            'specialists_about',
            'specialists',
            'services_block',
            'services',
            'technologies_block',
            'technologies',
            'helpful_block',
            'helpful',
            'questions_block',
            'problems',
            'stocks_block',
            'videos_block',
            'contacts',
            'testing_block',
        ]
];
